"""
Train standard FNO2d on 2D steady diffusion with internal obstacles.

Dataset format (generated by data_generation/generate_diffusion_obstacle2d.py):
    {
      'a_train': (n_train, N, N, 2),  # [geom, bc]
      'u_train': (n_train, N, N, 1),
      'a_test' : (n_test,  N, N, 2),
      'u_test' : (n_test,  N, N, 1),
    }

We treat this as a supervised mapping:
    (geom, bc) -> c
on a fixed N x N grid, to compare FNO2d and CFT-AO-2D on a complex-geometry
diffusion problem.
"""

import argparse
import os
from timeit import default_timer

import numpy as np
import torch
import torch.nn.functional as F

from fourier_2d_baseline import FNO2d
from utilities3 import UnitGaussianNormalizer, LpLoss, count_params
from Adam import Adam


def main(args):
    # reproducibility
    torch.manual_seed(int(args.seed))
    np.random.seed(int(args.seed))
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(int(args.seed))
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Seed: {int(args.seed)}")

    print(f"Loading diffusion-obstacle 2D dataset from {args.data_path} ...")
    try:
        data = torch.load(args.data_path, map_location="cpu")
        a_train_raw = data["a_train"]
        u_train_raw = data["u_train"]
        a_test_raw = data["a_test"]
        u_test_raw = data["u_test"]
    except Exception as e:
        print(f"Error loading data: {e}")
        return

    print(
        f"Shapes: a_train={tuple(a_train_raw.shape)}, u_train={tuple(u_train_raw.shape)}, "
        f"a_test={tuple(a_test_raw.shape)}, u_test={tuple(u_test_raw.shape)}"
    )

    # input normalization (optional)
    if args.no_a_norm:
        a_train = a_train_raw
        a_test = a_test_raw
        a_normalizer = None
        print("Input a: using RAW (no normalization).")
    else:
        a_normalizer = UnitGaussianNormalizer(a_train_raw)
        a_train = a_normalizer.encode(a_train_raw)
        a_test = a_normalizer.encode(a_test_raw)
        print("Input a: using UnitGaussianNormalizer.encode().")

    u_normalizer = UnitGaussianNormalizer(u_train_raw)
    u_train = u_normalizer.encode(u_train_raw)

    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(a_train, u_train),
        batch_size=args.batch_size,
        shuffle=True,
    )
    u_test_enc = u_normalizer.encode(u_test_raw)
    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(a_test, u_test_enc),
        batch_size=args.batch_size,
        shuffle=False,
    )
    if a_normalizer is not None:
        a_normalizer.to(device)
    u_normalizer.to(device)

    N = a_train.shape[1]
    in_channels = a_train.shape[-1]
    out_channels = u_train.shape[-1]

    model = FNO2d(
        modes1=args.modes,
        modes2=args.modes,
        width=args.width,
        in_channels=in_channels,
        out_channels=out_channels,
    ).to(device)

    print(f"\nModel: FNO2d (diffusion-obstacle)")
    print(f"Parameters: {count_params(model)}")
    print(
        f"Hyperparameters: Modes={args.modes}, Width={args.width}, "
        f"LR={args.learning_rate}, WeightDecay={args.weight_decay}"
    )

    optimizer = Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    # 与 Darcy2D 等脚本保持一致：使用 LpLoss (relative L2)，并在解码后再算 Raw Test L2
    # 注意：这是“相对 L2”，可以大于 1；为方便理解，下面也会同时统计像素级 MSE。
    loss_func = LpLoss(size_average=False)

    print("\n--- Starting Training (FNO2d diffusion-obstacle) ---")
    best_test = float("inf")

    for ep in range(args.epochs):
        model.train()
        t1 = default_timer()
        train_l2 = 0.0

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)

            optimizer.zero_grad()
            out = model(x)  # (B,N,N,1)
            loss = loss_func(out, y)
            loss.backward()
            optimizer.step()
            train_l2 += loss.item()

        scheduler.step()

        # eval：与 Darcy2D 训练脚本保持完全一致的相对 L2 / Raw L2 统计，
        # 同时增加一个更直观的像素级 MSE 指标，便于判断误差量级。
        model.eval()
        test_l2 = 0.0
        raw_test_l2 = 0.0
        mse_enc = 0.0
        mse_raw = 0.0
        mse_bdry = 0.0
        mse_obs = 0.0

        with torch.no_grad():
            # build Dirichlet mask on CPU once (outer boundary + obstacle interior)
            # NOTE: dataset a[...,0] is geom in {0,1}
            geom_test = a_test_raw[..., 0:1]  # (n_test,N,N,1)
            Btest = geom_test.shape[0]
            bdry = torch.zeros((Btest, N, N, 1), dtype=torch.bool)
            bdry[:, 0, :, :] = True
            bdry[:, -1, :, :] = True
            bdry[:, :, 0, :] = True
            bdry[:, :, -1, :] = True
            obs_mask = geom_test > 0.5
            dir_mask = bdry | obs_mask  # (n_test,N,N,1)

            offset = 0
            for x, y_enc in test_loader:
                x, y_enc = x.to(device), y_enc.to(device)
                out_enc = model(x)
                test_l2 += loss_func(out_enc, y_enc).item()
                # encoded-space MSE (sanity check)
                mse_enc += F.mse_loss(out_enc, y_enc, reduction="sum").item()

                out = u_normalizer.decode(out_enc)
                y = u_normalizer.decode(y_enc)
                raw_test_l2 += loss_func(out, y).item()
                # physical-space pixel MSE
                mse_raw += F.mse_loss(out, y, reduction="sum").item()

                # boundary/obstacle MSE in physical space
                bs = int(out.shape[0])
                dm = dir_mask[offset : offset + bs].to(device)  # bool
                dm_f = dm.to(out.dtype)
                mse_bdry += (((out - y) ** 2) * dm_f).sum().item()

                om = obs_mask[offset : offset + bs].to(device)
                mse_obs += (((out - y) ** 2) * om.to(out.dtype)).sum().item()
                offset += bs

        train_l2 /= a_train.shape[0]
        test_l2 /= a_test_raw.shape[0]
        raw_test_l2 /= a_test_raw.shape[0]
        # pixel MSE: divide by (#samples * N^2)
        num_test = a_test_raw.shape[0]
        num_pts = N * N
        mse_enc /= (num_test * num_pts)
        mse_raw /= (num_test * num_pts)
        mse_bdry /= (num_test * num_pts)
        mse_obs /= (num_test * num_pts)
        t2 = default_timer()

        if (ep + 1) % 10 == 0 or ep == 0:
            print(
                f"Epoch {ep+1}/{args.epochs} | Time: {t2-t1:.2f}s | "
                f"Train L2: {train_l2:.6f} | Test L2: {test_l2:.6f} | Raw Test L2: {raw_test_l2:.6f} | "
                f"Raw MSE(px): {mse_raw:.6e} | MSE(dirichlet px): {mse_bdry:.6e} | MSE(obs px): {mse_obs:.6e}"
            )

        if test_l2 < best_test - 1e-8:
            best_test = test_l2
            if args.model_save_path:
                best_path = args.model_save_path.replace(".pt", "_best.pt")
                best_dir = os.path.dirname(best_path)
                if best_dir and not os.path.exists(best_dir):
                    os.makedirs(best_dir, exist_ok=True)
                torch.save(model.state_dict(), best_path)

    print("--- Training Finished (FNO2d diffusion-obstacle) ---")
    if args.model_save_path:
        model_dir = os.path.dirname(args.model_save_path)
        if model_dir and not os.path.exists(model_dir):
            os.makedirs(model_dir, exist_ok=True)
        torch.save(model.state_dict(), args.model_save_path)
        yn_stats = {
            "mean": u_normalizer.mean.detach().cpu(),
            "std": u_normalizer.std.detach().cpu(),
        }
        yn_path = os.path.join(model_dir, "diff2d_fno_y_normalizer.pt")
        torch.save(yn_stats, yn_path)
        print(f"Model saved to {args.model_save_path}\nSaved u_normalizer stats to {yn_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train FNO2d on diffusion-obstacle 2D dataset.")
    parser.add_argument("--data_path", type=str, default="data/diffusion_obstacle2d_N64.pt")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--model_save_path",
        type=str,
        default="models/fno_diffusion_obstacle2d.pt",
        help="Where to save FNO2d model state_dict",
    )
    parser.add_argument("--modes", type=int, default=12)
    parser.add_argument("--width", type=int, default=64)
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument(
        "--no_a_norm",
        action="store_true",
        help="Disable input normalization on a=[geom,bc]. Useful when bc scale is important.",
    )

    args = parser.parse_args()
    main(args)


