"""
Train CFT-AO-2D (CFT_AO_2D_Atlas) on 2D steady diffusion with internal obstacles,
using Direction-A (A): boundary "constructive" Dirichlet extension + residual learning.

We enforce outer-boundary Dirichlet values by a cheap Coons-patch extension E[g],
and learn only a residual masked by a boundary window w(x):

    u_enc(x) = E_enc[g](x) + w(x) * r_enc_theta(x)

Dataset format (generated by data_generation/generate_diffusion_obstacle2d.py):
    {
      'a_train': (n_train, N, N, 2),  # [geom, bc]
      'u_train': (n_train, N, N, 1),
      'a_test' : (n_test,  N, N, 2),
      'u_test' : (n_test,  N, N, 1),
    }
"""

import argparse
import os
from timeit import default_timer

import numpy as np
import torch
import torch.nn.functional as F

from Adam import Adam
from boundary_ext_residual_2d import (
    ResidualOnDirichletExtension2D,
    ResidualOnDirichletExtension2D_MultiScale,
    _coons_patch_extension_from_bc,
    _harmonic_extension_jacobi,
)
from cft_ao_2d import CFT_AO_2D_Atlas
from utilities3 import LpLoss, UnitGaussianNormalizer, count_params


def main(args):
    # reproducibility
    torch.manual_seed(int(args.seed))
    np.random.seed(int(args.seed))
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(int(args.seed))
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Seed: {int(args.seed)}")

    print(f"Loading dataset from {args.data_path} ...")
    try:
        data = torch.load(args.data_path, map_location="cpu")
        a_train_raw = data["a_train"]
        u_train_raw = data["u_train"]
        a_test_raw = data["a_test"]
        u_test_raw = data["u_test"]
    except Exception as e:
        print(f"Error loading data: {e}")
        return

    print(
        f"Shapes: a_train={tuple(a_train_raw.shape)}, u_train={tuple(u_train_raw.shape)}, "
        f"a_test={tuple(a_test_raw.shape)}, u_test={tuple(u_test_raw.shape)}"
    )

    # input normalization (only for backbone input)
    a_normalizer = UnitGaussianNormalizer(a_train_raw)
    a_train = a_normalizer.encode(a_train_raw)
    a_test = a_normalizer.encode(a_test_raw)

    # output normalization (used by wrapper to build E_enc)
    u_normalizer = UnitGaussianNormalizer(u_train_raw)
    u_train = u_normalizer.encode(u_train_raw)
    u_test_enc = u_normalizer.encode(u_test_raw)

    # build "mixed" input: [a_norm (all channels), geom_raw, bc_raw]
    # IMPORTANT: always keep geom_raw/bc_raw as the LAST two channels so A-wrap
    # can locate them even when a has extra physics channels (e.g., coeff/src).
    geom_train_raw = a_train_raw[..., 0:1]
    bc_train_raw = a_train_raw[..., 1:2]
    geom_test_raw = a_test_raw[..., 0:1]
    bc_test_raw = a_test_raw[..., 1:2]
    x_train_mix = torch.cat([a_train, geom_train_raw, bc_train_raw], dim=-1)
    x_test_mix = torch.cat([a_test, geom_test_raw, bc_test_raw], dim=-1)

    train_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_train_mix, u_train),
        batch_size=args.batch_size,
        shuffle=True,
    )
    test_loader = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(x_test_mix, u_test_enc),
        batch_size=args.batch_size,
        shuffle=False,
    )

    a_normalizer.to(device)
    u_normalizer.to(device)

    in_channels = a_train.shape[-1]  # 2
    out_channels = u_train.shape[-1]  # 1

    backbone = CFT_AO_2D_Atlas(
        modes1=args.modes,
        modes2=args.modes,
        width=args.width,
        in_channels=in_channels,
        out_channels=out_channels,
        n_layers=args.n_layers,
        L_segments=args.cft_L,
        M_cheb=args.cft_M,
        L_segments_boundary=args.cft_L_boundary,
        M_cheb_boundary=args.cft_M_boundary,
        cft_res=args.cft_res,
        use_local=not args.no_local,
        rim_ratio=args.rim_ratio,
        cond_dim=2,
        inner_iters=args.inner_iters,
        n_bands=args.n_bands,
        n_sym_bases=args.n_sym_bases,
    ).to(device)

    if args.multiscale:
        coarse_backbone = CFT_AO_2D_Atlas(
            modes1=args.coarse_modes,
            modes2=args.coarse_modes,
            width=args.coarse_width,
            in_channels=in_channels,
            out_channels=out_channels,
            n_layers=args.coarse_layers,
            L_segments=args.cft_L,
            M_cheb=args.cft_M,
            L_segments_boundary=args.cft_L_boundary,
            M_cheb_boundary=args.cft_M_boundary,
            cft_res=args.cft_res,
            use_local=not args.no_local,
            rim_ratio=args.rim_ratio,
            cond_dim=2,
            inner_iters=args.inner_iters,
            n_bands=args.n_bands,
            n_sym_bases=args.n_sym_bases,
        ).to(device)
        model = ResidualOnDirichletExtension2D_MultiScale(
            backbone,
            coarse_backbone,
            y_mean=u_normalizer.mean,
            y_std=u_normalizer.std,
            in_channels_norm=in_channels,
            delta=args.delta,
            res_scale_init=args.res_scale_init,
            res_scale_max=args.res_scale_max,
            coarse_scale_init=args.coarse_scale_init,
            coarse_scale_max=args.coarse_scale_max,
            ext_method=args.ext_method,
            ext_iters=args.ext_iters,
            poisson_src_hidden=args.poisson_src_hidden,
            poisson_src_scale_max=args.poisson_src_scale_max,
            residual_clip=args.residual_clip,
            coarse_factor=args.coarse_factor,
            gamma_hidden=args.gamma_hidden,
            gamma_max=args.gamma_max,
            coarse_interior_eps=args.coarse_interior_eps,
        ).to(device)
    else:
        model = ResidualOnDirichletExtension2D(
            backbone,
            y_mean=u_normalizer.mean,
            y_std=u_normalizer.std,
            in_channels_norm=in_channels,
            delta=args.delta,
            res_scale_init=args.res_scale_init,
            res_scale_max=args.res_scale_max,
            ext_method=args.ext_method,
            ext_iters=args.ext_iters,
            poisson_src_hidden=args.poisson_src_hidden,
            poisson_src_scale_max=args.poisson_src_scale_max,
            residual_clip=args.residual_clip,
        ).to(device)

    # optional warm-start from a previous checkpoint (e.g., continue 30->60 epochs)
    init_ckpt = str(getattr(args, "init_ckpt_path", "") or "").strip()
    if init_ckpt:
        if not os.path.exists(init_ckpt):
            raise FileNotFoundError(
                f"--init_ckpt_path was provided but file does not exist: {init_ckpt}. "
                f"Refusing to start from scratch silently."
            )
        print(f"Warm-start: loading model state_dict from {init_ckpt}")
        state = torch.load(init_ckpt, map_location="cpu")
        model.load_state_dict(state, strict=True)

    print(f"\nModel: CFT_AO_2D_Atlas + A(residual-on-extension) (diffusion-obstacle)")
    print(f"Backbone parameters: {count_params(backbone)}")
    print(f"Total parameters: {count_params(model)}")
    hp = (
        f"Hyperparameters: Modes={args.modes}, Width={args.width}, "
        f"LR={args.learning_rate}, WeightDecay={args.weight_decay}, delta={args.delta}, "
        f"res_scale_init={args.res_scale_init}, res_scale_max={args.res_scale_max}, res_reg={args.res_reg}, "
        f"ext_method={args.ext_method}, ext_iters={args.ext_iters}"
    )
    if args.multiscale:
        hp += (
            f", multiscale=True, coarse_factor={args.coarse_factor}, coarse_modes={args.coarse_modes}, "
            f"coarse_width={args.coarse_width}, coarse_layers={args.coarse_layers}, "
            f"coarse_scale_init={args.coarse_scale_init}, coarse_scale_max={args.coarse_scale_max}, "
            f"gamma_hidden={args.gamma_hidden}, gamma_max={args.gamma_max}, coarse_interior_eps={args.coarse_interior_eps}"
        )
    print(hp)

    # optimizer (keep simple; reuse same as original cftao script)
    optimizer = Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    loss_func = LpLoss(size_average=False)

    print("\n--- Starting Training (CFT-AO + A, diffusion-obstacle) ---")
    best_test = float("inf")

    N = int(a_train_raw.shape[1])
    num_pts = N * N

    for ep in range(args.epochs):
        model.train()
        t1 = default_timer()
        train_l2 = 0.0

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            out = model(x)  # encoded
            loss = loss_func(out, y)

            # small residual energy regularization to prevent blowing up the interior
            if args.res_reg > 0:
                # r_enc is inside model.backbone; compute residual via (out - E_enc)
                # using wrapper-consistent E[g] (works for poisson_learned too).
                E_raw = model.build_extension_raw(x)
                E_enc = (E_raw - u_normalizer.mean) / (u_normalizer.std + 1e-12)
                res = out - E_enc
                loss = loss + float(args.res_reg) * (res**2).mean()
            loss.backward()
            optimizer.step()
            train_l2 += loss.item()

        scheduler.step()

        model.eval()
        test_l2 = 0.0
        raw_test_l2 = 0.0
        mse_raw = 0.0
        mse_bdry = 0.0
        mse_obs = 0.0
        mse_Eonly = 0.0
        cnt_bdry = 0.0
        cnt_obs = 0.0
        with torch.no_grad():
            for x, y_enc in test_loader:
                x, y_enc = x.to(device), y_enc.to(device)
                out_enc = model(x)
                test_l2 += loss_func(out_enc, y_enc).item()
                out = u_normalizer.decode(out_enc)
                y = u_normalizer.decode(y_enc)
                raw_test_l2 += loss_func(out, y).item()

                # pixel-wise MSE in raw space (more intuitive)
                mse_raw += F.mse_loss(out, y, reduction="sum").item()

                # boundary / obstacle MSE
                # x_mix: [a_norm(C), geom_raw(1), bc_raw(1)]
                geom_raw = x[..., in_channels : in_channels + 1]
                bc_raw = x[..., in_channels + 1 : in_channels + 2]
                # outer boundary mask
                bdry = torch.zeros_like(geom_raw, dtype=torch.bool)
                bdry[:, 0, :, :] = True
                bdry[:, -1, :, :] = True
                bdry[:, :, 0, :] = True
                bdry[:, :, -1, :] = True
                obs = geom_raw > 0.5
                dir_mask = bdry | obs

                # MSE on Dirichlet nodes (outer boundary + obstacles)
                diff2 = (out - y) ** 2
                mse_bdry += diff2[bdry].sum().item()
                mse_obs += diff2[obs].sum().item()
                cnt_bdry += float(bdry.sum().item())
                cnt_obs += float(obs.sum().item())

                # E-only baseline (no residual)
                E_raw = model.build_extension_raw(x)
                mse_Eonly += F.mse_loss(E_raw, y, reduction="sum").item()

        train_l2 /= a_train_raw.shape[0]
        test_l2 /= a_test_raw.shape[0]
        raw_test_l2 /= a_test_raw.shape[0]
        num_test = int(a_test_raw.shape[0])
        mse_raw /= (num_test * num_pts)
        mse_Eonly /= (num_test * num_pts)
        mse_bdry = mse_bdry / max(cnt_bdry, 1.0)
        mse_obs = mse_obs / max(cnt_obs, 1.0)
        t2 = default_timer()

        if (ep + 1) % 10 == 0 or ep == 0:
            extra = ""
            if str(args.ext_method) == "poisson_learned":
                try:
                    extra = (
                        f" | src_scale: {float(model.get_last_src_scale().detach().cpu()):.4f}"
                        f" | src_rms: {float(model.get_last_src_rms().detach().cpu()):.4e}"
                    )
                except Exception:
                    extra = ""
            if getattr(args, "multiscale", False):
                try:
                    # only available for multiscale wrapper
                    cs = float(model.get_coarse_scale().detach().cpu())
                    gm = float(model.get_last_gamma_mean().detach().cpu())
                    extra = extra + f" | coarse_scale: {cs:.4f} | gamma_mean: {gm:.4f}"
                except Exception:
                    pass
            print(
                f"Epoch {ep+1}/{args.epochs} | Time: {t2-t1:.2f}s | "
                f"Train L2: {train_l2:.6f} | Test L2: {test_l2:.6f} | Raw Test L2: {raw_test_l2:.6f} | "
                f"Raw MSE(px): {mse_raw:.6e} | E-only MSE(px): {mse_Eonly:.6e} | "
                f"MSE(bdry): {mse_bdry:.6e} | MSE(obs): {mse_obs:.6e} | "
                f"res_scale: {float(model.get_res_scale().detach().cpu()):.4f}"
                f"{extra}"
            )

        if test_l2 < best_test - 1e-8:
            best_test = test_l2
            if args.model_save_path:
                best_path = args.model_save_path.replace(".pt", "_best.pt")
                best_dir = os.path.dirname(best_path)
                if best_dir and not os.path.exists(best_dir):
                    os.makedirs(best_dir, exist_ok=True)
                torch.save(model.state_dict(), best_path)

    print("--- Training Finished (CFT-AO + A, diffusion-obstacle) ---")
    if args.model_save_path:
        model_dir = os.path.dirname(args.model_save_path)
        if model_dir and not os.path.exists(model_dir):
            os.makedirs(model_dir, exist_ok=True)
        torch.save(model.state_dict(), args.model_save_path)
        yn_stats = {
            "mean": u_normalizer.mean.detach().cpu(),
            "std": u_normalizer.std.detach().cpu(),
        }
        yn_path = os.path.join(model_dir, "diff2d_cftaoA_y_normalizer.pt")
        torch.save(yn_stats, yn_path)
        print(f"Model saved to {args.model_save_path}\nSaved u_normalizer stats to {yn_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train CFT_AO_2D_Atlas with A(residual-on-extension) on diffusion-obstacle 2D dataset."
    )
    parser.add_argument("--data_path", type=str, default="data/diffusion_obstacle2d_N64.pt")
    parser.add_argument(
        "--model_save_path",
        type=str,
        default="models/cftaoA_diffusion_obstacle2d.pt",
        help="Where to save wrapped model state_dict",
    )
    parser.add_argument(
        "--init_ckpt_path",
        type=str,
        default="",
        help="Optional warm-start checkpoint (a saved wrapped model state_dict). "
        "Useful to continue training without re-running early epochs.",
    )

    parser.add_argument("--modes", type=int, default=12)
    parser.add_argument("--width", type=int, default=64)
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=0)

    # CFT-AO backbone configs (same as train_cftao_diff2d_obstacle.py)
    parser.add_argument("--n_layers", type=int, default=4)
    parser.add_argument("--cft_L", type=int, default=4)
    parser.add_argument("--cft_M", type=int, default=4)
    parser.add_argument("--cft_L_boundary", type=int, default=8)
    parser.add_argument("--cft_M_boundary", type=int, default=8)
    parser.add_argument("--cft_res", type=int, default=0)
    parser.add_argument("--no_local", action="store_true")
    parser.add_argument("--rim_ratio", type=float, default=0.15)
    parser.add_argument("--inner_iters", type=int, default=2)
    parser.add_argument("--n_bands", type=int, default=3)
    parser.add_argument("--n_sym_bases", type=int, default=0)

    # A: boundary window thickness (in normalized coords)
    parser.add_argument(
        "--delta",
        type=float,
        default=0.05,
        help="Boundary ramp thickness for residual window w(x); w=0 on boundary, ~1 in interior.",
    )
    parser.add_argument(
        "--res_scale_init",
        type=float,
        default=0.02,
        help="Initial residual scaling (too small can stall learning due to gating).",
    )
    parser.add_argument(
        "--res_scale_max",
        type=float,
        default=0.25,
        help="Max residual scaling; effective scale is sigmoid(.) * res_scale_max.",
    )
    parser.add_argument(
        "--res_reg",
        type=float,
        default=1e-4,
        help="Residual energy regularization weight (0 to disable).",
    )
    parser.add_argument(
        "--ext_method",
        type=str,
        default="coons",
        choices=["zero", "coons", "harmonic", "poisson", "poisson_learned"],
        help="Boundary extension E[g] method.",
    )
    parser.add_argument(
        "--ext_iters",
        type=int,
        default=50,
        help="Jacobi iterations for harmonic/poisson extension (ignored for coons).",
    )
    parser.add_argument(
        "--poisson_src_hidden",
        type=int,
        default=32,
        help="Hidden width for learned Poisson source net (only for ext_method=poisson_learned).",
    )
    parser.add_argument(
        "--poisson_src_scale_max",
        type=float,
        default=1.0,
        help="Max scale for learned Poisson source (bounded via sigmoid).",
    )
    parser.add_argument(
        "--residual_clip",
        type=float,
        default=0.0,
        help="Apply tanh-clip on residual in encoded space to prevent blow-ups (0 disables).",
    )

    # multiscale residual operator (principle-level upgrade)
    parser.add_argument("--multiscale", action="store_true", help="Enable multiscale residual operator (fine + coarse).")
    parser.add_argument("--coarse_factor", type=int, default=2, help="Downsample factor for coarse branch.")
    parser.add_argument("--coarse_modes", type=int, default=8, help="Fourier/CFT modes for coarse backbone (lower -> more low-freq).")
    parser.add_argument("--coarse_width", type=int, default=32, help="Width for coarse backbone.")
    parser.add_argument("--coarse_layers", type=int, default=2, help="Number of layers for coarse backbone.")
    parser.add_argument("--coarse_scale_init", type=float, default=0.02, help="Initial scale for coarse residual branch.")
    parser.add_argument("--coarse_scale_max", type=float, default=0.25, help="Max scale for coarse residual branch.")
    parser.add_argument("--gamma_hidden", type=int, default=32, help="Hidden width for gamma(x) gating net.")
    parser.add_argument("--gamma_max", type=float, default=1.0, help="Max value for gamma(x) after sigmoid.")
    parser.add_argument(
        "--coarse_interior_eps",
        type=float,
        default=0.5,
        help="Only apply coarse branch where w(x) > eps (avoid boundary-adjacent pollution).",
    )

    main(parser.parse_args())


